#!/usr/bin/env python3
import numpy as np
import cv2
import torch
import math
from ultralytics import YOLO
from ultralytics.utils.nms import non_max_suppression

MAT_SIZE = 8

RUN_BOUNDING_BOXES = False
global_input_stream = []
next_stride, next_kernel, next_pad = 2, 3, 1

GLOBAL_BIASES = []
GLOBAL_SCALES = [] 

# --- Math Functions ---
def fixed28_to_float(fixed_val):
    return float(fixed_val) / (1 << 16)

def pack_8bit_to_256bit(pixel_array):
    word = 0
    for i, val in enumerate(pixel_array): word |= ((int(val) & 0xFF) << (i * 8))
    return word

def cpu_software_rewindow(raw_stream, h, w, c):
    tensor = np.zeros((h, w, c), dtype=np.int8)
    wpn = math.ceil(c / MAT_SIZE)
    for i in range(h * w):
        for w_idx in range(wpn):
            word = raw_stream[i * wpn + w_idx]
            for c_idx in range(MAT_SIZE):
                ch = w_idx * MAT_SIZE + c_idx
                if ch < c:
                    val = (word >> (c_idx * 8)) & 0xFF
                    tensor[i // w, i % w, ch] = val if val < 128 else val - 256
    padded = np.pad(tensor, ((next_pad, next_pad), (next_pad, next_pad), (0, 0)))
    new_s = []
    for y in range(0, padded.shape[0] - next_kernel + 1, next_stride):
        for x in range(0, padded.shape[1] - next_kernel + 1, next_stride):
            patch = padded[y:y+next_kernel, x:x+next_kernel, :].flatten()
            for i in range(0, len(patch), MAT_SIZE):
                chunk = patch[i:i+MAT_SIZE]
                if len(chunk) < MAT_SIZE: chunk = np.pad(chunk, (0, MAT_SIZE - len(chunk)))
                new_s.append(pack_8bit_to_256bit(chunk))
    return new_s

def main():
    global global_input_stream, GLOBAL_BIASES, GLOBAL_SCALES
    model = YOLO(r"linear_best.pt")
    img_rgb = cv2.cvtColor(cv2.resize(cv2.imread("eco_00060.png"), (512, 512)), cv2.COLOR_BGR2RGB)
    
    # Load scales generated by your compiler
    with open("scales.txt") as f:
        GLOBAL_SCALES = [float(l.strip()) for l in f]
        
    try:
        GLOBAL_BIASES = np.load("biases.npy", allow_pickle=True)
    except FileNotFoundError:
        print("ERROR: biases.npy not found! Re-run compiler.py!")
        return

    # Run Reference (PyTorch Uncompressed)
    gt = model(img_rgb, imgsz=512, conf=0.25, verbose=False)[0]
    for b in gt.boxes:
        x1, y1, x2, y2 = map(int, b.xyxy[0])
        cv2.rectangle(img_rgb, (x1, y1), (x2, y2), (255, 0, 0), 3)

    # Convert Image to Hardware Input Stream
    init_s = []
    img_q = (img_rgb.astype(np.float32)/255.0 * 127.0).astype(np.int8)
    for p in img_q.reshape(-1, 3):
        init_s.append(pack_8bit_to_256bit(np.pad(p, (0, MAT_SIZE-3))))
        
    global_input_stream = cpu_software_rewindow(init_s, 512, 512, 3)
    
    # Write initial layer stream to file for Vivado
    with open("flat_img.mem", "w") as f: 
        # Convert integers to 16-character (64-bit) hex strings
        f.write("\n".join([f"{val:016X}" for val in global_input_stream]))
    print("Wrote flat_img.mem for Vivado simulation.")

    if RUN_BOUNDING_BOXES:
        global_output_stream = []
        try:
            with open("img_output.mem") as f: 
                for l in f: 
                    # Use .append() instead of index assignment
                    global_output_stream.append(int(l.strip(), 16))
        except FileNotFoundError:
            print("Waiting for Vivado... 'img_output.mem' not found. Run simulation first!")
            return

        # Decode Final Tensor from Hardware Output
        grid, out_c = 16, 40
        data = np.zeros((grid, grid, out_c), dtype=np.float32)
        wpx = math.ceil(out_c/MAT_SIZE)
        
        for i in range(grid*grid):
            for w in range(wpx):
                # Ensure we don't read out of bounds if Vivado output is short
                if (i*wpx + w) < len(global_output_stream):
                    word = global_output_stream[i*wpx + w]
                    for c in range(MAT_SIZE):
                        if w*MAT_SIZE+c < out_c:
                            val = (word >> (c * 8)) & 0xFF
                            data[i//grid, i%grid, w*MAT_SIZE+c] = (val if val < 128 else val-256) / GLOBAL_SCALES[-1]
        
        hw_t = torch.tensor(data).permute(2, 0, 1).unsqueeze(0).to(next(model.parameters()).device)

        # --- DRIFT CORRECTION ---
        pt_img = torch.from_numpy(img_rgb).permute(2, 0, 1).unsqueeze(0).float() / 255.0
        pt_f = pt_img.to(hw_t.device)
        with torch.no_grad():
            for i in range(14): 
                pt_f = model.model.model[i](pt_f)
                
        hw_max = torch.max(torch.abs(hw_t)).item()
        pt_max = torch.max(torch.abs(pt_f)).item()
        
        print("\n" + "="*40)
        print("🔍 TENSOR QUANTIZATION DRIFT CHECK")
        print("="*40)
        print(f"Hardware Max Value: {hw_max:.4f}")
        print(f"PyTorch Target:     {pt_max:.4f}")
        
        if hw_max > 0:
            drift_ratio = pt_max / hw_max
            print(f"Applying Drift Correction Ratio: x{drift_ratio:.4f}")
            hw_t = hw_t * drift_ratio
        else:
            print("🚨 CRITICAL ERROR: Hardware output is completely DEAD (all zeros).")
        print("="*40 + "\n")
        
        with torch.no_grad():
            preds = model.model.model[-1]([hw_t])
            
        # FIX: Added explicit keyword arguments for NMS so it doesn't get confused!
        hwd = non_max_suppression(preds, conf_thres=0.0005, iou_thres=0.15)
        hwd = hwd[0] if len(hwd) > 0 else None
        
        if hwd is not None:
            for *box, conf, cls in hwd:
                x1, y1, x2, y2 = map(int, box)
                cv2.rectangle(img_rgb, (x1, y1), (x2, y2), (0, 255, 0), 2)
            print(f"SUCCESS: Found {len(hwd)} hardware cones!")
        else:
            print("SUCCESS: Found 0 hardware cones!")

        cv2.imwrite("npu_sim_output.jpg", cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB))
        print("Verification complete. Check npu_sim_output.jpg")

if __name__ == '__main__': main()